import puppeteer from 'puppeteer-core'
import chromium from '@sparticuz/chromium-min'
import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'

export const maxDuration = 60

export async function GET(
  request: Request,
  { params }: { params: { id: string } }
) {
  const cookieStore = cookies()
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() { return cookieStore.getAll() },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) =>
            cookieStore.set(name, value, options)
          )
        },
      },
    }
  )

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return new Response('Unauthorized', { status: 401 })
  }

  const { data: report } = await supabase
    .from('reports')
    .select('*, scans(*)')
    .eq('id', params.id)
    .eq('user_id', user.id)
    .single()

  if (!report) {
    return new Response('Not found', { status: 404 })
  }

  const { data: violations } = await supabase
    .from('violations')
    .select('*')
    .eq('scan_id', report.scan_id)
    .order('impact', { ascending: false })

  const scan = report.scans as any
  const score = scan?.compliance_score ?? 0
  const scoreColor = score >= 75 ? '#22D3A0'
    : score >= 50 ? '#F59E0B' : '#EF4444'

  const violationsRows = (violations || []).map((v: any) => `
    <tr style="border-bottom: 1px solid #2A2A3A;">
      <td style="padding: 10px; color: ${
        v.impact === 'critical' ? '#FF3B3B' :
        v.impact === 'serious' ? '#FF7A00' :
        v.impact === 'moderate' ? '#FFB800' : '#64B5F6'
      }; font-weight: bold; text-transform: uppercase; font-size: 11px;">
        ${v.impact || 'minor'}
      </td>
      <td style="padding: 10px; color: #F0F0FF; font-size: 12px;">
        ${v.rule_id || v.id || ''}
      </td>
      <td style="padding: 10px; color: #8B8BA7; font-size: 12px;">
        ${v.rule_description || v.description || ''}
      </td>
      <td style="padding: 10px; color: #8B8BA7; font-size: 11px;">
        ${v.fix_summary || v.help || ''}
      </td>
    </tr>
  `).join('')

  const html = `
    <!DOCTYPE html>
    <html><head><meta charset="utf-8"><style>
      * { margin:0; padding:0; box-sizing:border-box; }
      body { font-family: Arial, sans-serif; background:#0A0A0F;
        color:#F0F0FF; padding:40px; }
      .brand { color:#6C47FF; font-size:13px; font-weight:700;
        letter-spacing:2px; text-transform:uppercase; margin-bottom:10px;}
      .title { font-size:24px; font-weight:700; }
      .url { color:#8B8BA7; font-size:13px; margin-top:6px; }
      .date { color:#8B8BA7; font-size:12px; margin-top:2px; }
      .score-box { display:flex; gap:20px; align-items:center;
        background:#111118; border:1px solid #2A2A3A; border-radius:10px;
        padding:20px; margin:24px 0; }
      .score-num { font-size:48px; font-weight:800; color:${scoreColor}; }
      .stat { background:#0A0A0F; border-radius:6px; padding:10px 16px; }
      table { width:100%; border-collapse:collapse; margin-top:20px; }
      th { text-align:left; padding:8px 10px; color:#8B8BA7;
        font-size:11px; text-transform:uppercase; border-bottom:1px solid #2A2A3A; }
      .disclaimer { margin-top:30px; padding:14px; background:#111118;
        border:1px solid #2A2A3A; border-radius:8px; color:#8B8BA7; font-size:11px; }
    </style></head>
    <body>
      <div class="brand">WCAG Scanner</div>
      <div class="title">Accessibility Compliance Report</div>
      <div class="url">${scan?.url || ''}</div>
      <div class="date">Generated: ${new Date().toLocaleDateString()}</div>
      <div class="score-box">
        <div class="score-num">${score}</div>
        <div style="display:flex; gap:16px;">
          <div class="stat"><b style="color:#FF3B3B;">${scan?.critical_count ?? 0}</b> Critical</div>
          <div class="stat"><b style="color:#FF7A00;">${scan?.serious_count ?? 0}</b> Serious</div>
          <div class="stat"><b style="color:#FFB800;">${scan?.moderate_count ?? 0}</b> Moderate</div>
          <div class="stat"><b style="color:#64B5F6;">${scan?.minor_count ?? 0}</b> Minor</div>
        </div>
      </div>
      <table>
        <thead><tr><th>Impact</th><th>Rule</th><th>Description</th><th>Fix</th></tr></thead>
        <tbody>${violationsRows || '<tr><td colspan="4" style="padding:20px; color:#22D3A0;">No violations found</td></tr>'}</tbody>
      </table>
      <div class="disclaimer">
        This report was generated by automated scanning using axe-core.
        Automated scans detect approximately 57% of WCAG issues.
        Results do not constitute legal advice.
      </div>
    </body></html>
  `

  let browser = null
  try {
    const executablePath = await chromium.executablePath(
      'https://github.com/Sparticuz/chromium/releases/download/v127.0.0/chromium-v127.0.0-pack.tar'
    )

    browser = await puppeteer.launch({
      args: [...chromium.args, '--no-sandbox', '--disable-setuid-sandbox'],
      defaultViewport: { width: 1200, height: 1600 },
      executablePath,
      headless: true,
    })

    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'networkidle0' })

    const pdfBuffer = await page.pdf({
      format: 'a4',
      printBackground: true,
      margin: { top: '20px', bottom: '20px', left: '20px', right: '20px' }
    })

    return new Response(new Uint8Array(pdfBuffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="wcag-report-${params.id}.pdf"`
      }
    })
  } catch (err) {
    console.error('PDF generation failed:', err)
    return new Response('PDF generation failed', { status: 500 })
  } finally {
    if (browser) await browser.close()
  }
}